/*
 * population.js — builds the league-wide population for any statistic.
 *
 * THE TRICK
 * Every stat's compute() takes an object of named counting stats. The MLB API
 * rows use those same names (because api.js normalises them). So to get the
 * league distribution of ANY stat, we fetch every player and run the same
 * compute() function over each row.
 *
 * That means the curve and the top-100 table are never hardcoded. They are
 * generated by the identical formula the lesson just taught you — so if the
 * formula is right, the distribution is right.
 *
 * A stat declares its population with a `dist` object supporting five shapes:
 *
 *   { group: 'hitting' }                     run compute() over every hitter
 *   { group: 'hitting', field: 'RBI' }       read a column straight off the row
 *   { group: 'pitching', valueFn: fn }       custom function when compute()'s
 *                                            signature doesn't match a row
 *   { source: 'statcast', field: 'avgEV' }   a Baseball Savant leaderboard
 *   { values: [...] }                        a fixed set (park factors, etc.)
 */

import * as api from './api.js';
import { ctx } from './render.js';

const cache = new Map();

/* Minimum playing time before a player is included. Without a floor, a hitter
 * who went 1-for-2 in September posts a .500 average and wrecks the chart. */
const DEFAULT_MIN = {
  hitting: { field: 'PA', value: 150 },
  pitching: { field: 'outs', value: 90 },   // 30 innings
  fielding: { field: 'INN', value: 200 },
  team: null,
};

/* Every Baseball Savant leaderboard we can draw a population from. */
const SAVANT_SOURCES = {
  statcast:        (d) => api.statcastBatting(ctx.season),
  statcastPitch:   (d) => api.statcastPitching(ctx.season),
  expected:        (d) => api.expectedStats(ctx.season, d.minPA ?? 100),
  expectedPitcher: (d) => api.expectedStatsPitcher(ctx.season, d.minPA ?? 100),
  speed:           (d) => api.sprintSpeed(ctx.season, d.minRuns ?? 10),
  oaa:             (d) => api.outsAboveAverage(ctx.season),
  arm:             (d) => api.armStrength(ctx.season, d.minThrows ?? 50),
  poptime:         (d) => api.popTime(ctx.season, d.min2b ?? 5),
  batTracking:     (d) => api.batTracking(ctx.season, 'batter', d.minSwings ?? 100),
  pitchTracking:   (d) => api.batTracking(ctx.season, 'pitcher', d.minSwings ?? 100),
  activeSpin:      (d) => api.activeSpin(ctx.season, d.minSpin ?? 100),
};

/**
 * Returns { rows, values, ... } for a statistic.
 *   rows   — every qualifying entity with `value` attached, sorted best first
 *   values — just the numbers, for the histogram
 */
export async function populationFor(stat) {
  const key = `${stat.path}:${ctx.season}`;
  if (cache.has(key)) return cache.get(key);
  const promise = build(stat).catch((e) => { cache.delete(key); throw e; });
  cache.set(key, promise);
  return promise;
}

async function build(stat) {
  const d = stat.dist;
  if (!d) return null;

  // 1. A fixed set of values — park factors, run expectancy states, and other
  //    populations that are not made of players.
  if (d.values) {
    const rows = d.values.map((v) => (typeof v === 'number'
      ? { name: '', value: v }
      : { name: v.name, team: v.team ?? '', value: v.value }));
    return finish(rows, stat, d);
  }

  // 2. A Baseball Savant leaderboard.
  if (d.source) {
    const load = SAVANT_SOURCES[d.source];
    if (!load) throw new Error(`Unknown Savant source "${d.source}"`);
    const raw = await load(d);
    const rows = [];
    for (const r of raw) {
      if (d.min && (r[d.min.field] ?? 0) < d.min.value) continue;
      const value = d.valueFn ? safe(() => d.valueFn(r, ctx)) : r[d.field];
      if (value == null || !isFinite(value)) continue;
      rows.push({ ...r, value });
    }
    return finish(rows, stat, d);
  }

  // 3. Team level — all 30 clubs as one row each.
  if (d.group === 'team') {
    const raw = await api.teamRows(ctx.season);
    const rows = [];
    for (const r of raw) {
      const value = pickValue(stat, d, r);
      if (value == null || !isFinite(value)) continue;
      rows.push({ ...r, value });
    }
    return finish(rows, stat, d);
  }

  // 4. The normal case: fetch every player and run the lesson's own formula.
  const group = d.group ?? 'hitting';
  const raw = await api.leaders({ group, season: ctx.season, limit: 1500, qualified: false });
  const min = d.min ?? DEFAULT_MIN[group];

  /* Some stats need both worlds: MLB's counting stats (walks, strikeouts,
   * innings) AND Savant's batted-ball detail (ground balls, fly balls). The
   * `join` option merges a Savant leaderboard onto the MLB rows by player id,
   * which is what makes xFIP, SIERA and batted-ball profiles computable. */
  let joined = null;
  if (d.join) {
    const extra = await SAVANT_SOURCES[d.join](d);
    joined = new Map(extra.map((e) => [e.id, e]));
  }

  /* Everyone gets a value computed, including players below the playing-time
   * floor. The chart and the rankings use only qualifiers, but the search box
   * can still find a September call-up — flagged, so you know his rate stats
   * are built on very little. */
  const rows = [];
  for (const r of raw) {
    if (joined && !joined.has(r.id)) continue;

    // Rebuild PA if the endpoint didn't supply it (pitching rows have no PA).
    const row = { ...r, ...(joined ? joined.get(r.id) : null) };
    row.id = r.id;
    row.name = r.name;
    row.team = r.team;
    row.teamId = r.teamId;
    if (row.PA == null && row.AB != null) {
      row.PA = row.AB + (row.BB ?? 0) + (row.HBP ?? 0) + (row.SF ?? 0) + (row.SH ?? 0);
    }

    const value = pickValue(stat, d, row);
    if (value == null || !isFinite(value)) continue;
    row.value = value;
    row.qualified = !min || (row[min.field] ?? 0) >= min.value;
    rows.push(row);
  }
  return finish(rows, stat, d);
}

/** Column, custom function, or the stat's own compute() — in that order. */
function pickValue(stat, d, row) {
  if (d.field) return row[d.field];
  if (d.valueFn) return safe(() => d.valueFn(row, ctx));
  if (stat.compute) return safe(() => stat.compute(row, ctx));
  return null;
}

const safe = (fn) => { try { return fn(); } catch { return null; } };

function finish(all, stat, d) {
  const lower = d.lowerIsBetter ?? !!stat.lowerIsBetter;
  all.sort((a, b) => (lower ? a.value - b.value : b.value - a.value));

  // Anything without an explicit `qualified` flag (Savant leaderboards, fixed
  // value sets, teams) is already a qualifying population.
  const rows = all.filter((r) => r.qualified !== false);
  rows.forEach((r, i) => { r.rank = i + 1; });

  return {
    rows,                       // qualifiers only — the chart and the rankings
    allRows: all,               // everyone — what the search box looks through
    values: rows.map((r) => r.value),
    group: d.group ?? 'hitting',
    source: d.source ?? null,
    lowerIsBetter: lower,
    format: d.format ?? stat.format,
    label: d.label ?? stat.abbr,
    note: d.note ?? null,
    entity: d.group === 'team' ? 'club' : d.values ? 'value' : 'player',
  };
}

/** Human-readable description of the inclusion threshold, for the caption. */
export function minimumLabel(stat) {
  const d = stat.dist;
  if (!d) return '';
  if (d.values) return 'fixed reference set';
  if (d.group === 'team') return 'all 30 clubs';
  if (d.source) {
    if (d.source === 'speed') return `min ${d.minRuns ?? 10} competitive runs`;
    if (d.source === 'arm') return `min ${d.minThrows ?? 50} throws`;
    if (d.source === 'poptime') return `min ${d.min2b ?? 5} throws to 2nd`;
    if (d.source === 'batTracking' || d.source === 'pitchTracking') return `min ${d.minSwings ?? 100} swings`;
    if (d.source === 'expected' || d.source === 'expectedPitcher') return `min ${d.minPA ?? 100} PA`;
    return 'Statcast qualifiers';
  }
  const min = d.min ?? DEFAULT_MIN[d.group ?? 'hitting'];
  if (!min) return '';
  if (min.field === 'outs') return `min ${Math.round(min.value / 3)} innings pitched`;
  if (min.field === 'PA') return `min ${min.value} plate appearances`;
  if (min.field === 'INN') return `min ${min.value} innings fielded`;
  return `min ${min.value} ${min.field}`;
}

export function clearPopulationCache() {
  cache.clear();
}
